### ISSUE TITLE
fyi  - postgraphql (postres to graphql scaffolding)

### ISSUE THREAD

**Issue by johndpope** [robinjmurphy/ruby-graphql-server-example#3]
https://github.com/calebmer/postgraphql

I'd be interested to know how this compares when /if you have a chance to play with it.

I'm interested to fire up graphql on this project (open source facebook clone)
https://github.com/ging/social_stream/wiki/Social-Stream-database-schema

**Comment by robinjmurphy** [comment]
Thanks - that's an interesting project! Will take a look.
